### ISSUE TITLE
mac环境下失败。php跟node的容器没起来

### ISSUE THREAD

**Issue by Jackliu007888** [xiaoemoxiw/docker#2]
执行完docker-compose up -d 后，docker ps 当前运行的容器并没有PHP 跟 node

**Comment by xiaoemoxiw** [comment]
working_dir   你的这个目录下要有能运行的node环境。
docker logs node 来查看下是哪里出错了
docker ps -a 可以查看全部的容器，不加-a只能看到顺利启动的容器
